---
title: "Data Exploration and vizualization"
output: html_document
---

Classwork:

# data viz 1  1

```{r}
library(tidyverse)
library(ggridges)

weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

#scatter plot

ggplot(weather_df, aes(x=tmin, y=tmax, color = name)) +
        geom_point() + 
        geom_smooth(se = FALSE)

#another way

plot_info = weather_df %>%
            ggplot(aes(x=tmin, y=tmax))

plot_info + geom_point()

#faceting things
# . means don't make rows, ~names makes columns
#alpha in point is transparency
ggplot(weather_df, aes(x=tmin, y=tmax, color = name)) +
        geom_point(alpha=.3) + 
        geom_smooth(se = FALSE) + 
        facet_grid(.~name)
weather_df %>%
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = .5) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~name)
  
#univariate plot

weather_df %>%
  ggplot(aes(x = tmin, fill = name)) +
  geom_histogram(alpha=.5)
#color is weird in histograms, use fill

weather_df %>%
  ggplot(aes(x = tmin, fill = name)) +
  geom_histogram() +
 facet_grid(name ~ .)

weather_df %>%
  ggplot(aes(x = tmin, fill = name)) +
  geom_density(alpha = .3)

#trendy plots

weather_plot = weather_df %>%
  ggplot(aes(x=name, y=tmin, fill=name)) +
  geom_violin() +
  stat_summary()

ggsave("weather_plot.pdf", weather_plot, width= 8, height = 5)

```
```{r, fig.width=6, fig.height=3}
weather_plot
```

# Data viz and exploration II


```{r}
library(patchwork)
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) + 
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maxiumum daily temperature (C)",
    caption = "Data from the rnoaa package"
  ) + 
  scale_x_continuous(
    breaks = c(-15, 0, 15),
    labels = c("-15 c", "0", "15 c")
  ) + 
  scale_y_continuous(
    trans = 
  )

weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) + 
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maxiumum daily temperature (C)",
    caption = "Data from the rnoaa package") + 
  scale_color_hue(name = "Location", h = c(100, 300))
#line 116 is argument name not variable called name


weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) + 
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maxiumum daily temperature (C)",
    caption = "Data from the rnoaa package") + 
  viridis::scale_color_viridis(name = "Location", discrete = TRUE)
```
# Data Wrangling III

```{R}
pulse_data = haven::read_sas("./data_import_examples/public_pulse_data.sas7bdat")   %>% janitor::clean_names()
head(pulse_data)

#wide format to long format

pulse_long = pulse_data %>% pivot_longer(bdi_score_bl:bdi_score_12m , 
names_to = "visit",
names_prefix = "bdi_score_",
values_to = "bdi_score") %>% relocate(id, visit) %>% mutate(visit=recode(visit, "bl" = "00m"))

head(pulse_long)
```
Stacking data and binding rows

```{R}
fellowship_data = 
  readxl::read_excel("./data_import_examples/LotR_Words.xlsx", range = "B3:D6") %>% mutate(movie= "fellowship_ring")

two_towers_data = 
  readxl::read_excel("./data_import_examples/LotR_Words.xlsx", range = "F3:H6") %>% mutate(movie= "two_towers")

return_king_data = 
  readxl::read_excel("./data_import_examples/LotR_Words.xlsx", range = "J3:L6") %>% mutate(movie= "return_king")

lotr_tidy= bind_rows(fellowship_data, two_towers_data, return_king_data) %>%
  janitor::clean_names() %>% 
  relocate(movie) %>% 
  pivot_longer(female:male, names_to = "gender", values_to = "words")

```
joining datasets

```{R}
pup_data = 
  read_csv("./data_import_examples/FAS_pups.csv", col_types = "ciiiii") %>%
  janitor::clean_names() %>%
  mutate(sex = recode(sex, `1` = "male", `2` = "female")) 

litter_data = 
  read_csv("./data_import_examples/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  separate(group, into = c("dose", "day_of_tx"), sep = 3) %>%
  relocate(litter_number) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    dose = str_to_lower(dose))
#join litter data on to pups

left_join (pup_data, litter_data, by = "litter_number")
```

